server:
  port: 7001

spring:
  application:
    name: cyyaw-order-service
  jpa: #数据库配置
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  datasource:
    url: jdbc:mysql://192.168.1.102:3306/config?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: because
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart: ################## 上传文件
      max-file-size: 10MB
      max-request-size: 10MB

web:
  resources:
    photo:
      uploadPath: /etc/nginx/html/file
      BaseUrl: http://file.dishijiaoyu.com

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/