spring:
  application:
    name: cyyaw-spring-zuul

server:
  port: 9010

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/


# 构建路由地址
zuul:
  routes:
    # 这里可以自定义
    demo1:
      # 匹配的路由规则
      path: /**
      # 路由的目标服务名
      serviceId: cyyaw-order-web