spring:
  application:
    name: cyyaw-spring-boot-admin

server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/