spring:
  application:
    name: cyyaw-web-admin

server:
  port: 7031

eureka:
  instance:
    hostname: 192.168.0.100
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/