spring:
  application:
    name: cyyaw-eureka

server:
  port: 9090

eureka:
  instance:
    hostname: 192.168.1.130
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/