spring:
  application:
    name: cyyaw-web-admin

server:
  port: 7031

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/





feign:
  hystrix:
    enabled: true