server:
  port: 7009

spring:
  application:
    name: cyyaw-service-upload
  jpa: #数据库配置
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cyyaw_upload?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: because
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart: ################## 上传文件
      max-file-size: 10MB
      max-request-size: 10MB

web:
  resources:
    photo:
      uploadPath: J:/server/nginx-1.19.6/html/upload
      BaseUrl: http://file.cyyaw.com

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/