server:
  port: 9010

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/


spring:
  application:
    name: cyyaw-spring-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins:
              - "*"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600

      routes:
        - id: path1  # 路由的id,没有规定规则但要求唯一,建议配合服务名
          uri: lb://cyyaw-web-app # 匹配后提供服务的路由地址;   uri: http://localhost:8001
          predicates:
            - Path=/app/** # 断言，路径相匹配的进行路由
            - Path=/admin/**
            - Path=/tx/**
            - Path=/config/**
            - Path=/pc/**
            - Path=/store/**
        ###############    登录
        - id: path6
          uri: lb://cyyaw-service-sso
          predicates:
            - Path=/login/**
        - id: path2
          uri: lb://cyyaw-service-upload
          predicates:
            - Path=/upload/**
management:
  endpoints:
    web:
      exposure:
        # 当然暴露'*' 更好啦..
        include: gateway

