stages:
  - build
  - push
  - run
  - backfile


###############################   打包 jar
build:
  stage: build
  only:
    - master
  script:
    - pwd
    - mvn clean package -Dmaven.test.skip=true
    - scp docker/* root@192.168.0.100:spring_eureka/
    - scp target/eureka-0.0.1-SNAPSHOT.jar root@192.168.0.100:spring_eureka/

###############################   发送到目标机器的
push:
  stage: push
  script:
    - ssh -t root@192.168.0.100 "cd /root/spring_eureka && docker build -t spring_eureka ."


###############################   启动新服务
run:
  stage: run
  script:
    - ssh -t root@192.168.0.100 "cd /root/spring_eureka && docker-compose down && docker-compose up -d "



###############################   备份文件
backfile:
  stage: backfile
  script:
    - pwd













